execute if entity @s[name="CoreMRandom1"] run scoreboard players set @e[tag=corem.random,limit=1] corem.random 1
execute if entity @s[name="CoreMRandom2"] run scoreboard players set @e[tag=corem.random,limit=1] corem.random 2
execute if entity @s[name="CoreMRandom3"] run scoreboard players set @e[tag=corem.random,limit=1] corem.random 3
execute if entity @s[name="CoreMRandom4"] run scoreboard players set @e[tag=corem.random,limit=1] corem.random 4
execute if entity @s[name="CoreMRandom5"] run scoreboard players set @e[tag=corem.random,limit=1] corem.random 5
execute if entity @s[name="CoreMRandom6"] run scoreboard players set @e[tag=corem.random,limit=1] corem.random 6
execute if entity @s[name="CoreMRandom7"] run scoreboard players set @e[tag=corem.random,limit=1] corem.random 7
execute if entity @s[name="CoreMRandom8"] run scoreboard players set @e[tag=corem.random,limit=1] corem.random 8
execute if entity @s[name="CoreMRandom9"] run scoreboard players set @e[tag=corem.random,limit=1] corem.random 9
execute if entity @s[name="CoreMRandom10"] run scoreboard players set @e[tag=corem.random,limit=1] corem.random 10