scoreboard players reset * corem.count

execute as @e[type=minecraft:area_effect_cloud,distance=..100] run scoreboard players add area_effect_cloud corem.count 1
execute as @e[type=minecraft:armor_stand,distance=..100] run scoreboard players add armor_stand corem.count 1
execute as @e[type=minecraft:arrow,distance=..100] run scoreboard players add arrow corem.count 1
execute as @e[type=minecraft:bat,distance=..100] run scoreboard players add bat corem.count 1
execute as @e[type=minecraft:bee,distance=..100] run scoreboard players add bee corem.count 1
execute as @e[type=minecraft:blaze,distance=..100] run scoreboard players add blaze corem.count 1
execute as @e[type=minecraft:boat,distance=..100] run scoreboard players add boat corem.count 1
execute as @e[type=minecraft:cat,distance=..100] run scoreboard players add cat corem.count 1
execute as @e[type=minecraft:cave_spider,distance=..100] run scoreboard players add cave_spider corem.count 1
execute as @e[type=minecraft:chest_minecart,distance=..100] run scoreboard players add chest_minecart corem.count 1
execute as @e[type=minecraft:chicken,distance=..100] run scoreboard players add chicken corem.count 1
execute as @e[type=minecraft:cod,distance=..100] run scoreboard players add cod corem.count 1
execute as @e[type=minecraft:command_block_minecart,distance=..100] run scoreboard players add command_block_minecart corem.count 1
execute as @e[type=minecraft:cow,distance=..100] run scoreboard players add cow corem.count 1
execute as @e[type=minecraft:creeper,distance=..100] run scoreboard players add creeper corem.count 1
execute as @e[type=minecraft:dolphin,distance=..100] run scoreboard players add dolphin corem.count 1
execute as @e[type=minecraft:donkey,distance=..100] run scoreboard players add donkey corem.count 1
execute as @e[type=minecraft:dragon_fireball,distance=..100] run scoreboard players add dragon_fireball corem.count 1
execute as @e[type=minecraft:drowned,distance=..100] run scoreboard players add drowned corem.count 1
execute as @e[type=minecraft:egg,distance=..100] run scoreboard players add egg corem.count 1
execute as @e[type=minecraft:elder_guardian,distance=..100] run scoreboard players add elder_guardian corem.count 1
execute as @e[type=minecraft:end_crystal,distance=..100] run scoreboard players add end_crystal corem.count 1
execute as @e[type=minecraft:ender_dragon,distance=..100] run scoreboard players add ender_dragon corem.count 1
execute as @e[type=minecraft:ender_pearl,distance=..100] run scoreboard players add ender_pearl corem.count 1
execute as @e[type=minecraft:enderman,distance=..100] run scoreboard players add enderman corem.count 1
execute as @e[type=minecraft:endermite,distance=..100] run scoreboard players add endermite corem.count 1
execute as @e[type=minecraft:evoker,distance=..100] run scoreboard players add evoker corem.count 1
execute as @e[type=minecraft:evoker_fangs,distance=..100] run scoreboard players add evoker_fangs corem.count 1
execute as @e[type=minecraft:experience_bottle,distance=..100] run scoreboard players add experience_bottle corem.count 1
execute as @e[type=minecraft:experience_orb,distance=..100] run scoreboard players add experience_orb corem.count 1
execute as @e[type=minecraft:eye_of_ender,distance=..100] run scoreboard players add eye_of_ender corem.count 1
execute as @e[type=minecraft:falling_block,distance=..100] run scoreboard players add falling_block corem.count 1
execute as @e[type=minecraft:fireball,distance=..100] run scoreboard players add fireball corem.count 1
execute as @e[type=minecraft:firework_rocket,distance=..100] run scoreboard players add firework_rocket corem.count 1
execute as @e[type=minecraft:fox,distance=..100] run scoreboard players add fox corem.count 1
execute as @e[type=minecraft:furnace_minecart,distance=..100] run scoreboard players add furnace_minecart corem.count 1
execute as @e[type=minecraft:ghast,distance=..100] run scoreboard players add ghast corem.count 1
execute as @e[type=minecraft:giant,distance=..100] run scoreboard players add giant corem.count 1
execute as @e[type=minecraft:guardian,distance=..100] run scoreboard players add guardian corem.count 1
execute as @e[type=minecraft:hoglin,distance=..100] run scoreboard players add hoglin corem.count 1
execute as @e[type=minecraft:hopper_minecart,distance=..100] run scoreboard players add hopper_minecart corem.count 1
execute as @e[type=minecraft:horse,distance=..100] run scoreboard players add horse corem.count 1
execute as @e[type=minecraft:husk,distance=..100] run scoreboard players add husk corem.count 1
execute as @e[type=minecraft:illusioner,distance=..100] run scoreboard players add illusioner corem.count 1
execute as @e[type=minecraft:iron_golem,distance=..100] run scoreboard players add iron_golem corem.count 1
execute as @e[type=minecraft:item,distance=..100] run scoreboard players add item corem.count 1
execute as @e[type=minecraft:item_frame,distance=..100] run scoreboard players add item_frame corem.count 1
execute as @e[type=minecraft:leash_knot,distance=..100] run scoreboard players add leash_knot corem.count 1
execute as @e[type=minecraft:lightning_bolt,distance=..100] run scoreboard players add lightning_bolt corem.count 1
execute as @e[type=minecraft:llama,distance=..100] run scoreboard players add llama corem.count 1
execute as @e[type=minecraft:llama_spit,distance=..100] run scoreboard players add llama_spit corem.count 1
execute as @e[type=minecraft:magma_cube,distance=..100] run scoreboard players add magma_cube corem.count 1
execute as @e[type=minecraft:minecart,distance=..100] run scoreboard players add minecart corem.count 1
execute as @e[type=minecraft:mooshroom,distance=..100] run scoreboard players add mooshroom corem.count 1
execute as @e[type=minecraft:mule,distance=..100] run scoreboard players add mule corem.count 1
execute as @e[type=minecraft:ocelot,distance=..100] run scoreboard players add ocelot corem.count 1
execute as @e[type=minecraft:painting,distance=..100] run scoreboard players add painting corem.count 1
execute as @e[type=minecraft:panda,distance=..100] run scoreboard players add panda corem.count 1
execute as @e[type=minecraft:parrot,distance=..100] run scoreboard players add parrot corem.count 1
execute as @e[type=minecraft:phantom,distance=..100] run scoreboard players add phantom corem.count 1
execute as @e[type=minecraft:pig,distance=..100] run scoreboard players add pig corem.count 1
execute as @e[type=minecraft:piglin,distance=..100] run scoreboard players add piglin corem.count 1
execute as @e[type=minecraft:pillager,distance=..100] run scoreboard players add pillager corem.count 1
execute as @e[type=minecraft:polar_bear,distance=..100] run scoreboard players add polar_bear corem.count 1
execute as @e[type=minecraft:potion,distance=..100] run scoreboard players add potion corem.count 1
execute as @e[type=minecraft:pufferfish,distance=..100] run scoreboard players add pufferfish corem.count 1
execute as @e[type=minecraft:rabbit,distance=..100] run scoreboard players add rabbit corem.count 1
execute as @e[type=minecraft:ravager,distance=..100] run scoreboard players add ravager corem.count 1
execute as @e[type=minecraft:salmon,distance=..100] run scoreboard players add salmon corem.count 1
execute as @e[type=minecraft:sheep,distance=..100] run scoreboard players add sheep corem.count 1
execute as @e[type=minecraft:shulker,distance=..100] run scoreboard players add shulker corem.count 1
execute as @e[type=minecraft:shulker_bullet,distance=..100] run scoreboard players add shulker_bullet corem.count 1
execute as @e[type=minecraft:silverfish,distance=..100] run scoreboard players add silverfish corem.count 1
execute as @e[type=minecraft:skeleton,distance=..100] run scoreboard players add skeleton corem.count 1
execute as @e[type=minecraft:skeleton_horse,distance=..100] run scoreboard players add skeleton_horse corem.count 1
execute as @e[type=minecraft:slime,distance=..100] run scoreboard players add slime corem.count 1
execute as @e[type=minecraft:small_fireball,distance=..100] run scoreboard players add small_fireball corem.count 1
execute as @e[type=minecraft:snow_golem,distance=..100] run scoreboard players add snow_golem corem.count 1
execute as @e[type=minecraft:snowball,distance=..100] run scoreboard players add snowball corem.count 1
execute as @e[type=minecraft:spawner_minecart,distance=..100] run scoreboard players add spawner_minecart corem.count 1
execute as @e[type=minecraft:spectral_arrow,distance=..100] run scoreboard players add spectral_arrow corem.count 1
execute as @e[type=minecraft:spider,distance=..100] run scoreboard players add spider corem.count 1
execute as @e[type=minecraft:squid,distance=..100] run scoreboard players add squid corem.count 1
execute as @e[type=minecraft:stray,distance=..100] run scoreboard players add stray corem.count 1
execute as @e[type=minecraft:strider,distance=..100] run scoreboard players add strider corem.count 1
execute as @e[type=minecraft:tnt,distance=..100] run scoreboard players add tnt corem.count 1
execute as @e[type=minecraft:tnt_minecart,distance=..100] run scoreboard players add tnt_minecart corem.count 1
execute as @e[type=minecraft:trader_llama,distance=..100] run scoreboard players add trader_llama corem.count 1
execute as @e[type=minecraft:trident,distance=..100] run scoreboard players add trident corem.count 1
execute as @e[type=minecraft:tropical_fish,distance=..100] run scoreboard players add tropical_fish corem.count 1
execute as @e[type=minecraft:turtle,distance=..100] run scoreboard players add turtle corem.count 1
execute as @e[type=minecraft:vex,distance=..100] run scoreboard players add vex corem.count 1
execute as @e[type=minecraft:villager,distance=..100] run scoreboard players add villager corem.count 1
execute as @e[type=minecraft:vindicator,distance=..100] run scoreboard players add vindicator corem.count 1
execute as @e[type=minecraft:wandering_trader,distance=..100] run scoreboard players add wandering_trader corem.count 1
execute as @e[type=minecraft:witch,distance=..100] run scoreboard players add witch corem.count 1
execute as @e[type=minecraft:wither,distance=..100] run scoreboard players add wither corem.count 1
execute as @e[type=minecraft:wither_skeleton,distance=..100] run scoreboard players add wither_skeleton corem.count 1
execute as @e[type=minecraft:wither_skull,distance=..100] run scoreboard players add wither_skull corem.count 1
execute as @e[type=minecraft:wolf,distance=..100] run scoreboard players add wolf corem.count 1
execute as @e[type=minecraft:zombie,distance=..100] run scoreboard players add zombie corem.count 1
execute as @e[type=minecraft:zombie_horse,distance=..100] run scoreboard players add zombie_horse corem.count 1
execute as @e[type=minecraft:zombie_villager,distance=..100] run scoreboard players add zombie_villager corem.count 1
execute as @e[type=minecraft:zombie_horse,distance=..100] run scoreboard players add zombie_horse corem.count 1
execute as @e[type=minecraft:zombified_piglin,distance=..100] run scoreboard players add zombified_piglin corem.count 1

execute as @e[type=!minecraft:player,distance=..100] run scoreboard players add total corem.count 1